[package]
name = "rsndfile"
description = "libsndfile bindings for Rust (Î±lpha)"
version = "0.0.2"
repository = "https://github.com/eeeeeta/rsndfile"
readme = "README.md"
license = "Unlicense"
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]

[dependencies]
libc = "0.2.8"
